apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  type: ClusterIP
  selector:
    app: messaging-app-blue   # initially points to blue deployment
  ports:
    - port: 80
      targetPort: 8000
